<?php

/**
 * @file
 * File of the event.
 */

use Drupal\shrey_exercise\Event\UserLoginEvent;
use Drupal\Core\Entity\EntityInterface;
use Drupal\Core\Form\FormStateInterface;
use Drupal\Core\Entity\Display\EntityViewDisplayInterface;

/**
 * Function for hook theme.
 */
function shrey_exercise_theme($existing, $type, $theme, $path) {
  // Here we are initializing theme, template and the variables.
  return [
    'new_template' => [
      'variables' => [
        'markup' => "",
        'hexcode' => "",
      ],
    ],
  ];

}

/**
 * Here we implement hook_user_login().
 */
function shrey_exercise_user_login($account) {
  // Instantiate of the event.
  $event = new UserLoginEvent($account);

  // Get the event_dispatcher service and dispatch the event.
  $event_dispatcher = \Drupal::service('event_dispatcher');
  $event_dispatcher->dispatch($event, UserLoginEvent::EVENT_NAME);
}

/**
 * Implements hook_page_attachments_alter().
 */
function shrey_exercise_page_attachments_alter(array &$attachments) {
  // Here we are calling the service.
  $attachments['#attached']['library'][] = 'shrey_exercise/jss_lib';
  $attachments['#attached']['drupalSettings']['shrey_exercise']['vari_body'] = 'testing';
  $route_match = \Drupal::routeMatch();
  // Getting route name of the particular page here.
  $route_name = $route_match->getRouteName();
  // If the route name are same.
  if ($route_name === 'comment.admin') {
    // Apply the css.
    $attachments['#attached']['library'][] = 'shrey_exercise/shrey_exercise_styles';
  }
  // If the route name same.
  elseif ($route_name === 'entity.node.canonical') {
    // Apply the css.
    $attachments['#attached']['library'][] = 'shrey_exercise/shrey_exercise_styles';

  }
}

/**
 * Implements hook_entity_view_alter().
 */
function shrey_exercise_entity_view_alter(array &$build, EntityInterface $entity, EntityViewDisplayInterface $display) {
  if ($entity->getEntityTypeId() == "node") {
      $build['field_tags']['#title'] = "title from view alter";//changing the title
      unset($build['field_image']);//image field is removed
      $build['markup'] = [
          '#markup' => "<h3>Testing entity view alter hook</h3>",//static text we are adding
      ];
  }

}

/**
* Implements hook_entity_view().
*/
function shrey_exercise_entity_view(array &$build, EntityInterface $entity, EntityViewDisplayInterface $display, $view_mode) {
  // condition entity type = node
  $session = \Drupal::request()->getSession();
  $counts = $session->get("shrey_exercise.node_view_count", []);
  if (!isset($counts[$entity->id()])) {
      $counts[$entity->id()] = 1;
  }
  else {
      $counts[$entity->id()]++;
  }

  $session->set("shrey_exercise.node_view_count", $counts);
$build['count'] = [
  '#markup' => "Viewed " . $counts[$entity->id()] . " times",
  '#cache' => [
      'max-age' => 0,
  ],
];

}

/**
 * Implements hook_entity_presave().
 */
function shrey_exercise_entity_presave(EntityInterface $entity) {
  $entity->set("title", "presaving the values");
}

/**
 * Implements hook_form_alter().
 */
function shrey_exercise_form_alter(&$form, FormStateInterface $form_state, $form_id) {
  if ($form_id == "node_article_edit_form") {
    $helptext = \Drupal::configFactory()->getEditable("shrey_exercise.settings")->get("helptext");
    // type: node object.
    $node = \Drupal::routeMatch()->getParameter("node");
    $token_service = \Drupal::token();
    $hlptxt = $token_service->replace($helptext, ['node' => $node], ['clear' => TRUE]);
    $form['#prefix'] = "<span>" . $hlptxt . "</span>";
  }
}

/**
 * Implements hook_entity_insert().
 */
function shrey_exercise_entity_insert(EntityInterface $entity) {

  if ($entity->getEntityTypeId() !== 'node' || ($entity->getEntityTypeId() === 'node' && $entity->bundle() !== 'page')) {
    return;
  }

  $mailManager = \Drupal::service('plugin.manager.mail');

  $module = 'shrey_exercise';
  $key = 'create_page';
  $to = \Drupal::currentUser()->getEmail();
  $params['message'] = $entity->get('body')->value;
  $params['node_title'] = $entity->label();
  $langcode = \Drupal::currentUser()->getPreferredLangcode();
  $send = TRUE;

  $result = $mailManager->mail($module, $key, $to, $langcode, $params, NULL, $send);
  if ($result['result'] !== TRUE) {

    \Drupal::messenger()->addMessage(t('There was a problem sending your message and it was not sent'), 'error');
    // drupal_set_message.
  }
  else {

    \Drupal::messenger()->addMessage(t('There was a problem sending your message and it was not sent'), 'status');
    // drupal_set_message(t('Your message has been sent.'));.
  }

}

/**
 * Implements hook_mail().
 */
function shrey_exercise_mail($key, &$message, $params) {
  $options = [
    'langcode' => $message['langcode'],
  ];

  switch ($key) {
    case 'create_page':
      $message['from'] = \Drupal::config('system.site')->get('mail');
      $message['subject'] = t('Page created: @title', ['@title' => $params['node_title']], $options);
      $message['body'][] = $params['message'];
      break;
  }
}