<?php

/**
 * @file
 * File of the event.
 */

use Drupal\shrey_exercise\Event\UserLoginEvent;

/**
 * Function for hook theme.
 */
function shrey_exercise_theme($existing, $type, $theme, $path) {
  // Here we are initializing theme, template and the variables.
  return [
    'new_template' => [
      'variables' => [
        'markup' => "",
        'hexcode' => "",
      ],
    ],
  ];

}

/**
 * Here we implement hook_user_login().
 */
function shrey_exercise_user_login($account) {
  // Instantiate of the event.
  $event = new UserLoginEvent($account);

  // Get the event_dispatcher service and dispatch the event.
  $event_dispatcher = \Drupal::service('event_dispatcher');
  $event_dispatcher->dispatch($event, UserLoginEvent::EVENT_NAME);
}

/**
 * Implements hook_page_attachments_alter().
 */
function shrey_exercise_page_attachments_alter(array &$attachments) {
  // Here we are calling the service.
  $route_match = \Drupal::routeMatch();
  // Getting route name of the particular page here.
  $route_name = $route_match->getRouteName();
  // If the route name are same.
  if ($route_name === 'comment.admin') {
    // Apply the css.
    $attachments['#attached']['library'][] = 'shrey_exercise/shrey_exercise_styles';
  }
  // If the route name same.
  elseif ($route_name === 'entity.node.canonical') {
    // Apply the css.
    $attachments['#attached']['library'][] = 'shrey_exercise/shrey_exercise_styles';
  }
}
